# Generated by Django 4.2.2 on 2023-06-13 19:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
  
    dependencies = [
        ('store', '0006_alter_collection_featured_product_and_more'),
    ]

    operations = [
         migrations.RunSQL("""BEGIN;
                    --
                    -- Alter field id on cart
                    --
                    SET CONSTRAINTS "store_cartitem_cart_id_4f60ac05_fk_store_cart_id" IMMEDIATE; ALTER TABLE "store_cartitem" DROP CONSTRAINT "store_cartitem_cart_id_4f60ac05_fk_store_cart_id";
                    ALTER TABLE "store_cart" ALTER COLUMN "id" DROP IDENTITY IF EXISTS;
                    ALTER TABLE "store_cart" ALTER COLUMN "id" TYPE uuid USING gen_random_uuid();
                    DROP SEQUENCE IF EXISTS "store_cart_id_seq" CASCADE;
                    ALTER TABLE "store_cartitem" ALTER COLUMN "cart_id" TYPE uuid USING gen_random_uuid();
                    ALTER TABLE "store_cartitem" ADD CONSTRAINT "store_cartitem_cart_id_4f60ac05_fk" FOREIGN KEY ("cart_id") REFERENCES "store_cart" ("id") DEFERRABLE INITIALLY DEFERRED;
                    COMMIT;         
         """
        )
    ]

    """operations = [
         migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        )
    ]"""
